- platform: command_line
  switches:
    cam_salon_motion:
      command_on: !secret cam_salon_command_on
      command_off: !secret cam_salon_command_off
      command_state: !secret cam_salon_command_state
      value_template: '{{ value == "1" }}'
      friendly_name: Salon
