homeassistant: !include_dir_merge_named home/

frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_pwd
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5

#logger:
  #default: critical
  #logs:
  #  homeassistant.components.http: warning 

# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

ios:

notify: !include_dir_merge_named notify/

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60

zone: !include_dir_merge_named zones/
sensor: !include_dir_merge_named sensors/
shell_command: !include_dir_merge_named shell_commands/
camera: !include_dir_merge_named cameras/
switch: !include_dir_merge_named switches/
binary_sensor: !include_dir_merge_named binary_sensors/
#script: !include_dir_merge_named scripts/
group: !include_dir_merge_named groups/
automation: !include_dir_merge_named automations
