#- plateform: command_line
#  name: CPU Temp
#  commande: "cat /sys/class/thermal/thermal_zone0/temp"
#  unit_of_measurement: "°C"
#  value_template: '{{ value | multiply(0.001) }}'

#- platform: command_line
#  name: badlogin
#  command: "grep -c 'Login attempt' /home/hass/.homeassistant/home-assistant.log"

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: !secret ssl_cert_cmd

- platform: yr
  monitored_conditions:
    - symbol
    - temperature
    - windSpeed
  name: Meteo
